settings:
  # internal name of your game, example: "quake3"
  gamename: "unvanquished"
  # directory name for packages, example: "baseq3"
  basegame: "pkg"
  # entities format: "yaml" or "def"
  entities: "yaml"
